### ISSUE TITLE
[NEW FEATURE] Support for Wavelet Operator for direct use with ModOpt

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/pysap#107]
**Is your feature request related to a problem? Please describe.**
Currently pysap-mri implements a wavelet class that can be used with ModOpt for optimization.
https://github.com/CEA-COSMIC/pysap-mri/blob/master/mri/reconstruct/linear.py#L24
We notice that as we develop any other plugins in future, we may need this class repeatedly as Wavelet operator is important and comes up repeatedly for imaging applications with structured sparsity. 

**Describe the solution you'd like**
To prevent each plugin having a redundant implementation, we could have PySAP (or ModOpt: The location is still debatable) to have a general wavelet class that implements the Wavelet such that it can be used with ModOpt directly out of the box

**Are you planning to submit a Pull Request?**
- [X] Yes, Well it is just a basic class movement from pysap-mri to pysap, te base class at pysap-mri is pretty general at the moment.
- [ ] No

**Comment by sfarrens** [comment]
@chaithyagr is this something you are still working on?

**Comment by chaithyagr** [comment]
Not really @sfarrens , I am not sure if it is needed for me now. Earlier while I was working on `pysap-emicro`, it was with efforts to prevent common codes in multiple places. Right now I am just working on pysap-mri and I am comfortable in current state.. It is upto you if you want to close this or archive it for future

**Comment by sfarrens** [comment]
OK, I'll close it for now and we can reopen it if it becomes relevant again in the future.
