### ISSUE TITLE
[INSTALLATION ERROR] Import takes soo long

### ISSUE THREAD

**Issue by LElgueddari** [CEA-COSMIC/pysap#122]
**Describe the bug**
Pysap import is so long.
Could we remove the info fom the `__init__.py` file.

**Are you planning to submit a Pull Request?**
- [ ] Yes
- [X] No

**Comment by chaithyagr** [comment]
This is now fixed after #125. I have removed the info call

**Comment by chaithyagr** [comment]
@sfarrens / @AGrigis can we close this please?

**Comment by chaithyagr** [comment]
@sfarrens we can close this i think
