### ISSUE TITLE
[INSTALLATION ERROR]

### ISSUE THREAD

**Issue by dnc7309** [CEA-COSMIC/pysap#137]
**System setup**
OS: [e.g] Ubuntu 20.04 LTS
Python version: [e.g.] v3.8.2
Python environment (if any): [e.g.] 

**Describe the bug**
After installing all dependencies for ModOpt, PySAP and successfully pip installing all packages, I get an error related filter being not executable from the sparse2d module. After investigation in the sparse2d module, I was able to find the executable the error was pointing to (in the screen shots). I am trying to use this package with the Resolving Component Analysis and everything has been going smoothly up until this point. 

**To Reproduce**
Installed Ubunto, create a virtual environment (not with conda) and install Python and all standard packages (numpy, scipy, etc.). Installed ModOpt and all needed dependencies from the Github page. Installed PySAP with all dependencies through their online web page (https://python-pysap.readthedocs.io/en/latest/generated/installation.html). All packages cloned from Github were installed based on the setup.npy files provided. 

**Screenshots**
![OSError](https://user-images.githubusercontent.com/66930290/84683338-12016500-af05-11ea-9d74-55eaae0b4a8f.PNG)

The image below is a screenshot of the executable files from the iSAP zipped file found here (http://www.cosmostat.org/software/isap). 

![os](https://user-images.githubusercontent.com/66930290/84683436-32c9ba80-af05-11ea-894b-29d06c3bbb8e.PNG)

**Are you planning to submit a Pull Request?**
- [ ] Yes
- [X] No

**Comment by sfarrens** [comment]
Hi @dnc7309,

From your screenshot it looks like you are trying to run [RCA](https://github.com/CosmoStat/rca), am I right?

If so, then all you need is `ModOpt` and `Sparse2D`. RCA doesn't actually use PySAP directly. PySAP will, however, build both of these packages for you. If the installation was successful the Sparse2D binaries will be available, but you will need to manually update your path to find them. You can do so by simply running:

```bash
$ export PATH="<YOUR PATH TO PYSAP>/pysap/build/temp.<YOUR SYSTEM SPECS>/extern/bin:$PATH"
```

Let me know if this resolves your problem.

**Comment by dnc7309** [comment]
Hi Samuel, you are correct I am trying to run RCA. Their installation guide
stated installing PySAP should be easier than compiling iSAP myself.

Just some clarification, what is the <YOUR SYSTEM SPECS> represent and do I
run this line in my Ubunto command line? I am relatively new to Ubunto and
building these packages directly from Github.

Thank you so very much for the speedy reply, it is much appreciated!

**Comment by sfarrens** [comment]
Hi @dnc7309,

If (in a terminal) you go the directory where you cloned PySAP and ran the installation commands, you should see a `build` directory. Inside this directory there should be a subdirectory called `temp.<SOMETHING>`, where the `<SOMETHING>` depends on your system. On my system the directory is called `temp.macosx-10.9-x86_64-3.8` for the version of macOS and Python that I used to build PySAP. For you it should be something like `temp.ubuntu-...-3.8` or `temp.linux-...-3.8`. Once you know the correct name of this subdirectory, you can run the `export` command in a terminal.

Note that this will only be valid for the current session. If you want to keep this path for all sessions you should include this command in your `.bash_profile` or equivalent.

**Comment by dnc7309** [comment]
Hi Samuel, this worked! Thank you very much for your help.

**Comment by sfarrens** [comment]
Glad to hear it! 

I will close this issue now.
