### ISSUE TITLE
[BUG] Scikit-learn dependency causes failure when we do python setup.py install on python 3.5

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/pysap#138]
**System setup**
OS: Linux
Python version: [e.g.] v3.5
Python environment (if any): [e.g.] conda v4.5.11

**Describe the bug**
Scikit-learn has discontinued support for python3.5 . However, there are some post versions which can be installed. 
However, when we call `python setup.py install`, we fail with :

```
RuntimeError: Scikit-learn requires Python 3.6 or later. The current Python version is 3.5.2 installed in /volatile/Chaithya/Environments/temp/bin/python.
```

**To Reproduce**
Get a new python3.5 oenvironment, clone to this repository and do `python setup.py install`
We are currently failing in pysap-mri travis due to this.

**Module and lines involved**
We can just move scikit-learn as a preinstall requires to prevent this. Currently this issue is cropping up mainly because of a different flow used in stall when we invoke python setup.py install (through easy_install)

**Are you planning to submit a Pull Request?**
- [X] Yes
- [ ] No

**Comment by sfarrens** [comment]
Hi @chaithyagr see #135. I would prefer to avoid hacks to keep supporting Python 3.5. We can provide instructions for users to manually install older versions of Scikit-learn if needed.

**Comment by chaithyagr** [comment]
Hmm, well, although scikit-learn has dropped support, they still allow installs inside python3.5 environment. In my opinion, this is just an issue from `easy_install`, which ends up picking up the latest scikit-learn which wont work with python3.5 

This can be fixed if we just place scikit-learn as PREINSTALL_REQUIRES, as then pip will carry out installation (which is what we need ideally)

I am not sure if this is a hack as this is what we want for mostly all packages. This will ensure smooth installation for users, which in my opinion is really needed for a package to progress and get wider audience.

**Comment by sfarrens** [comment]
@chaithyagr That seems fine to me. All I want to avoid, in general, is forcing _e.g._ Python 3.8 to use an older version for Scikit-learn (or whatever) just to support Python 3.5 (which is quite outdated now).

**Comment by chaithyagr** [comment]
No no, we shall not force an older version. My PR would keep the same version, we just add it to preinstall requires so that pip can pickup the right version on its own
