### ISSUE TITLE
[BUG] FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated

### ISSUE THREAD

**Issue by patquem** [CEA-COSMIC/pysap#141]
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  fake_data[[(int(i[0]),) for i in list(zip(shape / 2))]] = 1

suggestion:
-> np.put(fake_data, fake_data.size // 2, 1)

**Comment by sfarrens** [comment]
Hi @patquem can you let me know from which module you have extracted this line?
```python
fake_data[[(int(i[0]),) for i in list(zip(shape / 2))]] = 1
```

**Comment by sfarrens** [comment]
The corresponding module is located in https://github.com/chaithyagr/pysap-etomo/blob/master/etomo/linear.py

Moving issues to corresponding repo and assigning to @chaithyagr.

**Comment by sfarrens** [comment]
Closing this issue as PySAP-ETomo is not currently hosted on CEA-COSMIC. If/when it is we can reopen and move the issue is necessary.
