### ISSUE TITLE
Adding paper to the Readme

### ISSUE THREAD

**Issue by zaccharieramzi** [CEA-COSMIC/pysap#144]
We should have the Pysap paper linked in the readme with an associated bibtex citation in order for people to more easily reference this work.

**Comment by philouc** [comment]
Absolutely ; here is the bibtex reference : 
@article{farrens2020pysap,
  title={{PySAP: Python Sparse Data Analysis Package for multidisciplinary image processing}},
  author={Farrens, S and Grigis, A and El Gueddari, L and Ramzi, Z and Chaithya, GR and Starck, S and Sarthou, B and Cherkaoui, H and Ciuciu, P and Starck, J-L},
  journal={Astronomy and Computing},
  volume={32},
  pages={100402},
  year={2020},
  publisher={Elsevier}
}
