### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by SylvainLan** [CEA-COSMIC/pysap#18]
Hi everyone,

I just finished installing pisap on my device after some problems solved thanks to @LElgueddari and @AGrigis . 

I will make a list of those errors so that it can be checked in the future : 
- NFFT is needed, and furthermore the 3.2.4 version seems more suitable. In the newer versions a specific file (nfft3util.h) is removed from the include folder and raises errors when installing pynfft with pip
- Sparse2D is needed also on its own. When installing pisap, I guess that a pruned version of sparse2d is added but some binaries are missing, like mr_transform. Therefore the dependencies of Sparse2D are also compulsory (e.g. cfitsio). 
- In sf_tools/signal/optimisation.py there is an error if line 463 is not commented when using CONDAT
- I still have a deprecation warning when loading pisap concerning pyfits, but I guess it's just a dependency issue
- Obviously all the libraries installed previously have to be properly linked in the PATH.

Maybe all of those errors are obvious for you but as @LElgueddari advised me to, I supposed you'd be interested in my experience as a new user.

**Comment by AGrigis** [comment]
Thank you for your feedbacks:
* For the NFFT we will generate a document to explain how to install the optional module.
* We will put a note in the installation documentation regarding this point. Note that we prefer users to use the pysparse module that is somehow simply a binding of these commands.
* The optimisation module has been fixed.
* We now use astropy to load the FITS images.
* We will generate a document that with explains in detail all the installation steps
