### ISSUE TITLE
Installation problems on Ubuntu (17.10)

### ISSUE THREAD

**Issue by rmyleroy** [CEA-COSMIC/pysap#30]
Here is a list of solutions I have been using to solve problems I have encountered while installing pISAP on my machine (Ubuntu 17.10).

- Install CMake package using `sudo apt install cmake` for the `python setup.py develop --user` command to run properly.

- PyQtGraph requires one of PyQt4, PyQt5 or PySide. Solved using `sudo apt install python-qt4`.

**Comment by AGrigis** [comment]
Thank you for your feedback.
We will add a detailed installation documentation for LINUX and MAC in order to check that all the module dependencies are installed properly.
