### ISSUE TITLE
scapy version download error for python3

### ISSUE THREAD

**Issue by SylvainLan** [CEA-COSMIC/pysap#35]
I am trying to install pysap for python3.6 directly through pip install for my anaconda python

When trying to pip install pysap, I get the following error message

> Collecting pysap
  Using cached pysap-0.1.14.zip
Collecting scapy==2.3.3 (from pysap)
  Using cached scapy-2.3.3.tgz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-j1kx12h6/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token

I checked with python2, this syntax is valid but for python3 it should be 
`os.chmod(fname, 0o755)`

For python3 we should be installing scapy3 I guess.

**Comment by AGrigis** [comment]
Thanks for your feedback.

Note that your error comes from scapy:
"/tmp/pip-build-j1kx12h6/scapy/setup.py, line 36"
Please report these bug in the scapy issue tracker.

Nonetheless, I noticed there were missing files in the pysap package.
I added these files, version to install is now 0.0.2.
I installed successfully pysap using the 'pip3 install --user --upgrade python-pysap' command.
