### ISSUE TITLE
Lipschitz constant not taken into account in plugins.mri.reconstruct.reconstruc.sparse_rec_fista

### ISSUE THREAD

**Issue by SylvainLan** [CEA-COSMIC/pysap#39]
The Lipschitz constant is calculated but not put in the ForwardBackward function, making the cost function to explode when L is too big (end set in the algorithm to 1)

A quick fix is to set the 'beta_param' 

Maybe it could be a better idea to automatically fetch the inv_spec_rad argument of gradient, but it would need more work.

**Comment by LElgueddari** [comment]
@sfarrens This even should be fixed at the modopt level: if the fista acceleration is used then the _beta param sould be set as gradient_op.inv_spec_rad
