### ISSUE TITLE
Istransform attribute

### ISSUE THREAD

**Issue by JulienNGirard** [CEA-COSMIC/pysap#4]
Add a way to print in which space the transform currently is.

e.g.
```
wl=WaveletTransformBase.REGISTRY[-mywavelet-]
wl.data=image
wl.istransform()
```
===> return FALSE
```
wl.analysis()
wl.istransform()
```
===> return TRUE

**Comment by AGrigis** [comment]
The original image is stored in the class 'data' attribute.
Then, after analysis, the data are stored in the 'analysis_data'.
The synthesis method generates a new image.

I think we do not need an extra parameter?

**Comment by philouc** [comment]
At the first glance, this seems far better than before
