### ISSUE TITLE
Wrong installation instructions with pip

### ISSUE THREAD

**Issue by jeremiedecock** [CEA-COSMIC/pysap#42]
Installation instructions in https://cea-cosmic.github.io/pysap/generated/installation.html are wrong:

> pip install --user pysap

_pysap_ corresponds to a completely different package on PyPI. _pysap_ is a "Python library for crafting SAP's network protocols packets".

See https://pypi.org/project/pysap/

**Comment by AGrigis** [comment]
Thank you for your remark.
As you can see in the readme pypi badge we decided to register our project as 'python-pySAP' since 'pysap' was already used.
We will update the documentation to fix this issue.
