### ISSUE TITLE
Wrong reference to pypipe

### ISSUE THREAD

**Issue by jeremiedecock** [CEA-COSMIC/pysap#43]
_pypipe_ is defined as an extra dependency in https://github.com/CEA-COSMIC/pysap/blob/master/pysap/info.py#L87

_pypipe_ corresponds to a completely different package on PyPI (https://pypi.org/project/pypipe/) and thus pip install a wrong dependency with pysap.

Also, there are several Python packages named _pypipe_ on internet and there is no reference to the right one in pysap documentation. I guess the right package is this one: https://github.com/AGrigis/pypipe (it should be mentionned somewhere in pysap documentation).

**Comment by AGrigis** [comment]
We can fix this issue using the dependency_links setup option.

**Comment by AGrigis** [comment]
Since setup URLs are not really supported:
- remove this from dependencies.
- add a user message.
