### ISSUE TITLE
Fail to compile PySAP dependencies on MacOSX using Anaconda and MacPorts

### ISSUE THREAD

**Issue by jeremiedecock** [CEA-COSMIC/pysap#45]
Here are the commands I use to compile and install PySAP on MacOSX using Anaconda and MacPorts
(the environment.yml is available there: https://raw.githubusercontent.com/jeremiedecock/pysap/master/environment.yml )

```
# Install cmake and GCC7 with MacPorts (in /opt/local)
sudo port install cmake gcc7

# Make the conda virtual environment and activate it
conda env create -f environment.yml
source activate pysap

# Set the compiler environment variable (to use the right MacPorts version of GCC)
export CC="/opt/local/bin/gcc-mp-7"
export CXX="/opt/local/bin/g++-mp-7"

# Set the Python headers directory (here in the Anaconda pysap virtual environment)
export CPLUS_INCLUDE_PATH=~/anaconda3/envs/pysap/include/python3.6m

# Build and install
python3 setup.py build
python3 setup.py install
```

It can compile but it cannot link.
I also tried with Python2.7 and I’ve got the same errors.
I'll try with _homebrew_ instead of _macports_.

**Comment by sfarrens** [comment]
With #88 PySAP can be built on macOS in any of the following ways:

1. Using the native `AppleClang` and `libomp` from Homebrew.

```bash
brew install libomp
python setup.py install
```

2. Using `gcc` from Homebrew.

```bash
brew install gcc
export CC=gcc-8
export CXX=g++-8
python setup.py install
```

All methods have been tested using `conda 4.6.2` and the following environment.

```bash
conda create -n pysap python=3.6 pyqtgraph
```
