### ISSUE TITLE
Wrong installation instructions using git clone

### ISSUE THREAD

**Issue by philouc** [CEA-COSMIC/pysap#64]
We should provide the following instruction line: 
git clone https://github.com/CEA-COSMIC/pysap

instead of git clone https://github.com/neurospin/pysap

**Comment by AGrigis** [comment]
Just waiting for documentation refresh.

**Comment by sfarrens** [comment]
Issue resolved in latest HTML documentation update.

https://cea-cosmic.github.io/pysap/generated/installation.html
