### ISSUE TITLE
Wrong name pywavelet in 3D

### ISSUE THREAD

**Issue by Martin11847** [CEA-COSMIC/pysap#68]
`from pysap.numerics.utils import generate_operators`, one can initialize a 3D linear operator with one of the pyWavelet wavelet like `Db4`, but cannot use it in 3D getting this error:
`ValueError: This wavelet can only be applied on 2D square images`
But when we take the `from pysap.plugins.mri.reconstruct_3D.linear import pyWavelet3` the names are different `pyWavelet3("Db4")` is now unrecognised however `pyWavelet3("db4")` is fine. 
Inconsistency between wavelet names in `pywt` and `pysap.pywt` wavelets.

**Comment by AGrigis** [comment]
Use pywt names.
Will be fixed after PR #85 merge.
