### ISSUE TITLE
Program running problem: No module named mri.numberics.fourier

### ISSUE THREAD

**Issue by tianxiaoxiao2018** [CEA-COSMIC/pysap#89]
Hi,
I have a problem, just like the picture shows.
![深度截图_选择区域_20190329195352](https://user-images.githubusercontent.com/43208155/55231786-a202b280-525e-11e9-86c3-0640a36af10b.png)

Do you have some suggestions?

Thanks for your help,
TianXiaoxiao

**Comment by AGrigis** [comment]
Hi,
Did you install pysap-mri on your machine?
Best.

**Comment by AGrigis** [comment]
The plugin is in dev, please install from URL:
pip install --user git+https://github.com/CEA-COSMIC/pysap-mri.git

**Comment by tianxiaoxiao2018** [comment]
Thanks for your reply. I'll try against.

**Comment by tianxiaoxiao2018** [comment]
Thank you for your reply.I'll try again.

**Comment by sfarrens** [comment]
@tianxiaoxiao2018 Is this still an issue for you?
