### ISSUE TITLE
Installation of mri plugin fails

### ISSUE THREAD

**Issue by zaccharieramzi** [CEA-COSMIC/pysap#91]
Right now when trying to install `pysap` with `pip install -e .`, it fails [because the plugins are not released on pypi](https://github.com/CEA-COSMIC/pysap/issues/86#issuecomment-477153237). Maybe before that we could have a fix, by allowing the install to [take the plugins from github instead of pypi](https://github.com/CEA-COSMIC/pysap/blob/master/pysap/info.py#L82-L83).

**Comment by philouc** [comment]
We should figure this out in the coming weeks. Otherwise, people won"t look at Pysap anymore. Antoine will be back on Mon

**Comment by sfarrens** [comment]
@zaccharieramzi, unfortunately that does not seem to work very well. @AGrigis and I worked for a day on various ways to build the plug-ins directly from GitHub, but it is not very reliable. 

The current plan is to make formal release of PySAP (this month) with development releases of the plugins on pypi.

**Comment by chaithyagr** [comment]
I think the main issue here is resolved, however this does open a new issue of having to point pysap installation to latest version of `pysap-mri`, without which the installation is quite convoluted right now. I will open a new issue for this, although we do have a PR #140 in flight for this.

**Comment by sfarrens** [comment]
From the last PySAP coding sprint it was decided that we would have scheduled PySAP releases 3 or 4 times per year. For each new release (major, minor or patch) we can update the fixed plug-in versions used by PySAP.  Developers can always manually change plug-in versions for testing.

Unless there objections I will close this issue.
