### ISSUE TITLE
[INSTALLATION ERROR]

### ISSUE THREAD

**Issue by philouc** [CEA-COSMIC/pysap#97]
**System setup**
OS: [e.g] Linux Ubuntu 18.04 LTS
Python version: [e.g.] v3.6.8
Python environment (if any): 

**Describe the bug**
Problem on the binding of sparse2d with pybind11 at the installation step.
pysparse.cpp:17:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(pysparse, module)

**To Reproduce**
    • pip3 install modopt
    • export CC=/usr/bin/gcc
    • export CXX=/usr/bin/g++
    • git clone https://github.com/CEA-COSMIC/pysap.git
    • sudo apt install pybind11-dev
    •  python3 setup.py develop –user (failed up to now)

**Screenshots**
See attached

**Are you planning to submit a Pull Request?**
- [ ] Yes
- [X] No
![Capture d’écran de 2019-08-05 11-04-30](https://user-images.githubusercontent.com/6186118/62452617-ddfbd600-b770-11e9-8efd-fa5fceda3a60.png)

**Comment by sfarrens** [comment]
@philouc I suggest you try the following:

```bash
$ export CC=/usr/bin/gcc
$ export CXX=/usr/bin/g++
$ git clone https://github.com/CEA-COSMIC/pysap.git
$ cd pysap
$ python3 setup.py develop –user 
```

You should not need to pre-install ModOpt or pybind11. If, for some reason you do on your system, try simply running `$ pip install pybind11`.

If this raises the same error, try building from PR #95.

```bash
$ export CC=/usr/bin/gcc
$ export CXX=/usr/bin/g++
$ git clone https://github.com/CEA-COSMIC/pysap.git
$ cd pysap
$ git fetch origin pull/95/head:pr-95
$ git checkout pr-95
$ python3 setup.py develop –user 
```

**Comment by philouc** [comment]
I did  $ pip install pybind11 and checked that pybind11 was actually properly installed by testing its import from python3.

Then I tried both above mentioned schemes but none of them fixes the issue. I have the feeling that "array.resize" in the **class pybind11::array_t<float>** should be renamed array.size as outlined in the attached 
 
![Capture d’écran de 2019-08-05 13-32-37](https://user-images.githubusercontent.com/6186118/62461604-93d11f80-b785-11e9-83f2-884f43d1bc6b.png)

**Comment by AGrigis** [comment]
I will make an explicit allocation:

auto array = py::array(py::buffer_info(
        nullptr,            /* Pointer to data (nullptr -> ask NumPy to allocate!) */
        sizeof(float),     /* Size of one item */
        py::format_descriptor<double>::value, /* Buffer format */
        2,          /* How many dimensions? */
       {image.nl(), image.nc()},  /* Number of elements for each dimension */
        { sizeof(float) }  /* Strides for each dimension */
    ));
auto  buffer = array.request();

Hope it can help.

**Comment by AGrigis** [comment]
Sam can you try compiling pysap using gcc 7.4.0 (the one available on ubuntu 18.04)?
Thx.

**Comment by sfarrens** [comment]
@AGrigis I was able to build it on my Mac using gcc 7.4.0 with no issues.

**Comment by AGrigis** [comment]
OK, seems to be a pybind11 install conflict.
When installing in local we need to export the CPLUS_INCLUDE_PATH before.

**Comment by sfarrens** [comment]
Perhaps we can make a PR to automate this for installation with the `--user` option.

**Comment by chaithyagr** [comment]
Is this still an issue? I think this was addressed in some PR..

**Comment by sfarrens** [comment]
@philouc is this still an issue? If so we can try to resolve this for the next release, if not I will close this issue.

**Comment by philouc** [comment]
No you can close it as it's no longer an issue.
