### ISSUE TITLE
[INSTALLATION ERROR] Name collision?

### ISSUE THREAD

**Issue by jacobtomlinson** [CEA-COSMIC/pysap#98]
I'm currently watching the talk about this project at euroscipy. Sounds awesome!

To learn more I googled `pysap` which lead me to [this repository](https://github.com/SecureAuthCorp/pysap) instead.

Interestingly both the install instructions [here](https://cea-cosmic.github.io/pysap/generated/installation.html) and in [that project](https://github.com/SecureAuthCorp/pysap) are:

```console
$ pip install pysap
```

Has there been a naming collision?

**Comment by philouc** [comment]
Yes, there is

 You should run:
pip3 install --user python-pySAP

or: 
pip3 install git+https://github.com/CEA-COSMIC/pysap

Take care about exporting the env variable  CPLUS_INCLUDE_PATH:
export CPLUS_INCLUDE_PATH=/usr/include/python3.x

More details can be found here:
https://github.com/CEA-COSMIC/pysap/issues/97

**Comment by jacobtomlinson** [comment]
Ok sure. Could the cosmic documentation be updated to have the correct pip install command?

**Comment by sfarrens** [comment]
This issue appears to be resolved in the current HTML documentation.

https://cea-cosmic.github.io/pysap/generated/installation.html
