### ISSUE TITLE
[HELP] Why is there a restriction that incoming data must be square?

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/pysap#99]
I would like to work with 3D wavelet transforms but I see that currently in base transform.py, there is restriction that incoming data must be square:
https://github.com/CEA-COSMIC/pysap/blob/a798315626b60108fbf598ba9c15228ea3c0b206/pysap/base/transform.py#L223-L224
Can we make the raise error to a warning?

**Comment by chaithyagr** [comment]
Just noting here that, this particular error prevents from using pysap for 3D with shape N*N*Nz, although PyWavelets support it with right padding.
@AGrigis / @sfarrens  Maybe, we dont raise this error if we are accessing pywt?
I could get a PR for this if this is fine and good immediate solution.

**Comment by sfarrens** [comment]
Resolved in #102
